### ISSUE TITLE
Issues after deploy api - Pool is destroyed error

### ISSUE THREAD

**Issue by rustyb** [AmericanRedCross/osm-stats#43]
Hi All - have been trying to deploy the osm-stats services to AWS today. I had to make a few changes to the deploy script but thats no problem.

Have run into the following issues once everything is set up. If I look at the logs from the stats-api docker container, everything I visit `instanceurl/users` the following error comes up. I tried to upgrade to a newer version of Knex but the same error persists.

I can connect from my local machine to the postgres instance with no issues. Wondering has anyone come across this before?

Below is the error as printed:

```
May  5 10:36:13 ip-172-31-41-190 docker/df31aeb1ce40[3064]: Unhandled rejection Error: Pool is destroyed
May  5 10:36:13 ip-172-31-41-190 docker/df31aeb1ce40[3064]:     at Pool.acquire (/usr/src/osm-stats-api-0.4.0/node_modules/knex/node_modules/pool2/lib/pool.js:162:12)
May  5 10:36:13 ip-172-31-41-190 docker/df31aeb1ce40[3064]:     at /usr/src/osm-stats-api-0.4.0/node_modules/knex/lib/client.js:204:19
May  5 10:36:13 ip-172-31-41-190 docker/df31aeb1ce40[3064]:     at tryCatcher (/usr/src/osm-stats-api-0.4.0/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23)
May  5 10:36:13 ip-172-31-41-190 docker/df31aeb1ce40[3064]:     at Promise._resolveFromResolver (/usr/src/osm-stats-api-0.4.0/node_modules/knex/node_modules/bluebird/js/main/promi$
May  5 10:36:13 ip-172-31-41-190 docker/df31aeb1ce40[3064]:     at new Promise (/usr/src/osm-stats-api-0.4.0/node_modules/knex/node_modules/bluebird/js/main/promise.js:71:37)
May  5 10:36:13 ip-172-31-41-190 docker/df31aeb1ce40[3064]:     at Client.acquireConnection (/usr/src/osm-stats-api-0.4.0/node_modules/knex/lib/client.js:200:12)
May  5 10:36:13 ip-172-31-41-190 docker/df31aeb1ce40[3064]:     at /usr/src/osm-stats-api-0.4.0/node_modules/knex/lib/runner.js:136:49
May  5 10:36:13 ip-172-31-41-190 docker/df31aeb1ce40[3064]:     at tryCatcher (/usr/src/osm-stats-api-0.4.0/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23)
May  5 10:36:13 ip-172-31-41-190 docker/df31aeb1ce40[3064]:     at Function.Promise.attempt.Promise.try (/usr/src/osm-stats-api-0.4.0/node_modules/knex/node_modules/bluebird/js/ma$
May  5 10:36:13 ip-172-31-41-190 docker/df31aeb1ce40[3064]:     at Runner.ensureConnection (/usr/src/osm-stats-api-0.4.0/node_modules/knex/lib/runner.js:135:26)
May  5 10:36:13 ip-172-31-41-190 docker/df31aeb1ce40[3064]:     at Runner.run (/usr/src/osm-stats-api-0.4.0/node_modules/knex/lib/runner.js:30:31)
May  5 10:36:13 ip-172-31-41-190 docker/df31aeb1ce40[3064]:     at QueryBuilder.Target.then (/usr/src/osm-stats-api-0.4.0/node_modules/knex/lib/interface.js:27:43)
May  5 10:36:13 ip-172-31-41-190 docker/df31aeb1ce40[3064]:     at QueryBuilder.tryCatcher (/usr/src/osm-stats-api-0.4.0/node_modules/bookshelf/node_modules/bluebird/js/main/util.$
May  5 10:36:13 ip-172-31-41-190 docker/df31aeb1ce40[3064]:     at doThenable (/usr/src/osm-stats-api-0.4.0/node_modules/bookshelf/node_modules/bluebird/js/main/thenables.js:52:38)
May  5 10:36:13 ip-172-31-41-190 docker/df31aeb1ce40[3064]:     at tryConvertToPromise (/usr/src/osm-stats-api-0.4.0/node_modules/bookshelf/node_modules/bluebird/js/main/thenables$
May  5 10:36:13 ip-172-31-41-190 docker/df31aeb1ce40[3064]:     at Promise._resolveCallback (/usr/src/osm-stats-api-0.4.0/node_modules/bookshelf/node_modules/bluebird/js/main/prom$
May  5 10:36:13 ip-172-31-41-190 docker/df31aeb1ce40[3064]:     at Promise._settlePromiseFromHandler (/usr/src/osm-stats-api-0.4.0/node_modules/bookshelf/node_modules/bluebird/js/$
May  5 10:36:13 ip-172-31-41-190 docker/df31aeb1ce40[3064]:     at Promise._settlePromiseAt (/usr/src/osm-stats-api-0.4.0/node_modules/bookshelf/node_modules/bluebird/js/main/prom$
May  5 10:36:13 ip-172-31-41-190 docker/df31aeb1ce40[3064]:     at Async._drainQueue (/usr/src/osm-stats-api-0.4.0/node_modules/bookshelf/node_modules/bluebird/js/main/async.js:12$
May  5 10:36:13 ip-172-31-41-190 docker/df31aeb1ce40[3064]:     at Async._drainQueues (/usr/src/osm-stats-api-0.4.0/node_modules/bookshelf/node_modules/bluebird/js/main/async.js:1$
May  5 10:36:13 ip-172-31-41-190 docker/df31aeb1ce40[3064]:     at Immediate.Async.drainQueues [as _onImmediate] (/usr/src/osm-stats-api-0.4.0/node_modules/bookshelf/node_modules/$
May  5 10:36:13 ip-172-31-41-190 docker/df31aeb1ce40[3064]:     at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by sethfitz** [comment]
This has been fixed in the current version of osm-stats-api.
